"""Add revoked_token table.

Revision ID: c3f1b9a8d2e4
Revises: 0763d677d453
Create Date: 2025-10-27 00:00:00.000000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c3f1b9a8d2e4"
down_revision = "0763d677d453"
branch_labels = None
depends_on = None


def upgrade():
    """Create the revoked_token table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "revoked_token",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("jti", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("jti"),
    )
    # ### end Alembic commands ###


def downgrade():
    """Drop the revoked_token table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("revoked_token")
    # ### end Alembic commands ###
