name: requirements-check

on:
  push:
    branches: [ fix/requirements ]
  pull_request:
    branches: [ fix/requirements ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install pip
        run: python -m pip install --upgrade pip
      - name: Install requirements
        run: |
          python -m pip install -r requirements.txt